### ISSUE TITLE
can't compile in delphi xe7!

### ISSUE THREAD

**Issue by kevinsui581** [da-baranov/SciDe#2]
when compile in xe7, sciter.pas compiled error:E2010 Incompatible types:'PUINT' and 'cardinal'

in line 1744:

```
OleCheck(pLang.ConvertStringFromUnicode(pdwMode, enc, PWideChar(Html), psrcSize, nil, pcDstSize));
```

**Comment by da-baranov** [comment]
Fixed, sorry. Tested in D7 as my Delphi 7 XE trial has expired.
